on: [push]

name: CI

jobs:
  build:
    name: Check and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
